### ISSUE TITLE
library soname differs between installed filename and needed library name

### ISSUE THREAD

**Issue by vicamo** [intel/ipu6-camera-bins#2]
```
$ readelf -d lib/libia_camera.so|grep Shared
 0x0000000000000001 (NEEDED)             Shared library: [libia_isp_bxt.so]
 0x0000000000000001 (NEEDED)             Shared library: [libia_log.so]
 0x0000000000000001 (NEEDED)             Shared library: [libia_cipf.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgcss.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```
While the suggested way to install these libraries in the [README.md](https://github.com/intel/ipu6-camera-bins/blob/main/README.md) is:
```
$ cp -r ipu6-camera-bins/lib/* /usr/lib/
```
But some of the sonames of required libraries have `.0` suffix, this is pretty confusing and takes special care in packaging them in a formal way. Please correct all the sonames to have `.0` suffix and update README.

**Comment by cjechlitschek** [comment]
Vicamo, what would be a proper way to install those libraries?

**Comment by vicamo** [comment]
> Vicamo, what would be a proper way to install those libraries?

The problem here is that you ship your libraries with file name `libia_camera.so`, and yet it has SONAME `libia_camera.so.0`; file name `libgcss.so`, but SONAME `libgcss.so.0`; and yet others, for example, with file name `libia_cmc_parser.so` ans SONAME also `libia_cmc_parser.so`. It doesn't follow general Unix way and is confusing when trying to package/install them.

The perfect way, like `libstdc++.so.6` and `libc.so.6`, is to provide an ABI number in their SONAME fields, and install as `libstdc++.so.6` and `libc.so.6` correspondingly:
```
$ readelf -d /lib/x86_64-linux-gnu/libc.so.6|grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libc.so.6]
 ```
 So whenever your library has some major update that breaks existing ABI, you may bump them so your precious clients using them will stay unaffected, and transitions can be made easily. Since your `libia_camera.so` has already a SONAME with ABI number, you should have known how to specify it, then just specify that for all the generated blobs. Only plugin share libraries, if any, should skip this. Then a symbolic link for each of them should be provided, e.g. `libia_camera.so -> libia_camera.so.1`, That's because in pkgconfig file we usually have `-lia_camera` only.

The full action items following this way should be:
1. specify version info for all share libraries, so linker would create SONAME field with ABI suffix,
2. ship share libraries with file names like `libfoo.so.1`,
3. update your documentation and details the need of creating symbolic link for them for development purpose: , e.g. `libfoo.so -> libfoo.so.1`.

The not-so-perfect way is to strip number suffix to all the files (as what you do) and their SONAME field. Then versioning is no longer available. I personally won't take this method. I'd prefer do it right at the beginning, not digging holes for myself in the future.

**Comment by wytIntel** [comment]
Hi Vicamo,
we don't have version control for all share libraries.  we build out all the share libraries from one code release. using libs from different release is not suggested.  will remove the suffix in next release. really thank you for this finding
