### ISSUE TITLE
Andrew MLK (Latitude 9403) failed with 2022-11-12 release for RPL PV

### ISSUE THREAD

**Issue by KaiChuan-Hsieh** [intel/ipu6-camera-bins#35]
The latest code drop for Oasis RPL PV failed on ADL Andrew MLK.

Here is the log:
[mipi-camera-failed.zip](https://github.com/intel/ipu6-camera-bins/files/10284135/mipi-camera-failed.zip)

**Comment by ccgjimlai** [comment]
Looking from the log, the privacy pin was enabled
Dec 22 11:10:29 ubuntu kernel: vsc_csi spi-INTC1094:00-92335fcf-3203-4472-af93-7b4453ac29da: privacy on, command id = 0

In that case, no MIPI data will be passed to IPU and HAL.

**Comment by KaiChuan-Hsieh** [comment]
@ccgjimlai 
Thanks for the reply, the camera works after toggle the camera shutter.
